#!/bin/tcsh
#/usr/bin/bash

# ./testmode3 N M1 M2 M3 T B
mkdir -p hdl
cp testgen gen 3layer_template.sv *txt conv_template* *tcl  hdl/
cd hdl
rm -rf work
vlib work
./testgen 3 $1 $2 $3 $4 $5 $6 
./gen 3 $1 $2 $3 $4 $5 $6 const_$1_$2_$3_$4_$5_$6.txt 
vlog net_$1_$2_$3_$4_$5_$6.sv tb_net_$1_$2_$3_$4_$5_$6.sv 
vsim -c tb_net_$1_$2_$3_$4_$5_$6 -do "run -all; quit"
#0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 
set clk = (0.9 0.95 1 1.05 1.1 1.15 1.2 1.25 1.3 1.35 1.4 1.45 1.5 1.55 1.6 1.65 1.7 1.75 1.8)

set j = 1
echo "net_$1:q_$2:q_$3:q_$4:q_$5:q_$6:q" #> "net_$1:q_$2:q_$3:q_$4:q_$5:q_$6:q.txt"
while ($j < 27)
sed -i -e 's/set TOP_MOD_NAME .*/set TOP_MOD_NAME '"net_$1:q_$2:q_$3:q_$4:q_$5:q_$6:q"'/' runsynth.tcl
sed -i -e 's/set SRC_FILE .*/set SRC_FILE '"net_$1:q_$2:q_$3:q_$4:q_$5:q_$6:q.sv"'/' runsynth.tcl
sed -i -e 's/set CLK_PERIOD .*/set CLK_PERIOD '"$clk[$j]"'/' runsynth.tcl
dc_shell -f runsynth.tcl #>> "net_$1:q_$2:q_$3:q_$4:q_$5:q_$6:q.txt"
@ j++
end

#sed -i -e 's/set TOP_MOD_NAME .*/set TOP_MOD_NAME '"conv_$1_$2_$3_$4"'/' runsynth.tcl
#sed -i -e 's/set SRC_FILE .*/set SRC_FILE '"conv_$1_$2_$3_$4.sv"'/' runsynth.tcl
#dc_shell -f runsynth.tcl
cd ../
