#!/usr/bin/bash

# ./testmode2 N M T P
./testgen 2 $1 $2 $3 $4
./gen 2 $1 $2 $3 $4 const_$1_$2_$3_$4.txt 
vlog conv_$1_$2_$3_$4.sv tb_conv_$1_$2_$3_$4.sv 
vsim -c tb_conv_$1_$2_$3_$4 -do "run -all; quit"
#sed -i -e 's/set TOP_MOD_NAME .*/set TOP_MOD_NAME '"conv_$1_$2_$3_$4"'/' runsynth.tcl
#sed -i -e 's/set SRC_FILE .*/set SRC_FILE '"conv_$1_$2_$3_$4.sv"'/' runsynth.tcl
#dc_shell -f runsynth.tcl
